---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app fstrim
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      fstrim:
        type: cronjob
        cronjob:
          schedule: 0 0 * * 1
          timeZone: ${TIMEZONE}
          parallelism: 1 # Set to my total number of nodes
          successfulJobsHistory: 1
          failedJobsHistory: 1
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/kubanetics
              tag: 2025.2.2@sha256:e4a45a5ad0f538554dd8220542f27ec7a9306390f5de68cdebfb02b7a8311fc5
            env:
              SCRIPT_NAME: fstrim.sh
            securityContext:
              privileged: true
    defaultPodOptions:
      hostNetwork: true
      hostPID: true
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: *app
    persistence:
      procfs:
        type: hostPath
        hostPath: /proc
        hostPathType: Directory
        globalMounts:
          - path: /host/proc
            readOnly: true
      netfs:
        type: hostPath
        hostPath: /sys
        hostPathType: Directory
        globalMounts:
          - path: /host/net
            readOnly: true
