---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi
spec:
  interval: 30m
  chart:
    spec:
      chart: democratic-csi
      version: 0.14.7
      sourceRef:
        name: democratic-csi
        kind: HelmRepository
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    csiDriver:
      name: local-hostpath.democratic-csi.k8s.home.arpa
      storageCapacity: true
      attachRequired: false
      fsGroupPolicy: File
    storageClasses:
      - name: democratic-csi-hostpath
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: WaitForFirstConsumer
        allowVolumeExpansion: false
    volumeSnapshotClasses:
      - name: csi-democratic-csi-hostpath
        deletionPolicy: Delete
        parameters:
          cluster: k8s
    controller:
      enabled: true
      strategy: node
      externalProvisioner:
        enabled: true
      externalResizer:
        enabled: false
      externalAttacher:
        enabled: false
      externalSnapshotter:
        enabled: true
    node:
      driver:
        image: ghcr.io/democratic-csi/democratic-csi:v1.9.2
        extraVolumeMounts:
          - name: local-hostpath
            mountPath: &path /var/mnt/extra/democratic-csi/local
            mountPropagation: Bidirectional
      extraVolumes:
        - name: local-hostpath
          hostPath:
            path: *path
            type: DirectoryOrCreate
    driver:
      config:
        driver: local-hostpath
        instance_id: k8s-local-hostpath
        local-hostpath:
          shareBasePath: *path
          controllerBasePath: *path
          dirPermissionsMode: "0770"
          dirPermissionsUser: 0
          dirPermissionsGroup: 0
