---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: democratic-csi
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.15.0
  url: oci://ghcr.io/democratic-csi/charts/democratic-csi
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi
spec:
  chartRef:
    kind: OCIRepository
    name: democratic-csi
  interval: 1h
  values:
    csiDriver:
      name: local-hostpath.democratic-csi.k8s.home.arpa
      storageCapacity: true
      attachRequired: false
      fsGroupPolicy: File
    storageClasses:
      - name: democratic-csi-hostpath
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: WaitForFirstConsumer
        allowVolumeExpansion: false
    volumeSnapshotClasses:
      - name: csi-democratic-csi-hostpath
        deletionPolicy: Delete
        parameters:
          cluster: k8s
    controller:
      enabled: true
      strategy: node
      externalProvisioner:
        enabled: true
      externalResizer:
        enabled: false
      externalAttacher:
        enabled: false
      externalSnapshotter:
        enabled: true
    node:
      driver:
        extraVolumeMounts:
          - name: local-hostpath
            mountPath: &path /var/mnt/local-hostpath
            mountPropagation: Bidirectional
      extraVolumes:
        - name: local-hostpath
          hostPath:
            path: *path
            type: DirectoryOrCreate
    driver:
      config:
        driver: local-hostpath
        instance_id: k8s-local-hostpath
        local-hostpath:
          shareBasePath: *path
          controllerBasePath: *path
          dirPermissionsMode: "0770"
          dirPermissionsUser: 0
          dirPermissionsGroup: 0
