---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly
spec:
  image: ghcr.io/dragonflydb/dragonfly:v1.26.0
  replicas: 1
  args:
    - --proactor_threads=2
    - --cluster_mode=emulated
    - --lock_on_hashtags
