---
clients:
  qb:
    create_tags_upfront: false
    download_path: /media/downloads/torrents/complete
    enabled: true
    filter: default
    type: qbittorrent
    url: http://qbittorrent.media.svc.cluster.local

filters:
  default:
    MapHardlinksFor:
      - retag

    ignore:
      - IsTrackerDown()
      - Downloaded == false && !IsUnregistered()
      - SeedingHours < 26 && !IsUnregistered()

    remove:
      - IsUnregistered()
      - (
          HasAnyTag(
            "site:ANT", "site:AR", "site:AT", "site:FL", "site:FNP",
            "site:IPT", "site:MLK", "site:TD",
          ) &&
          Ratio > 3.0
        )
      - (
          HasAnyTag(
            "site:ANT", "site:AR", "site:AT", "site:BLU", "site:FL",
            "site:FNP", "site:HDT", "site:IPT", "site:MLK", "site:PHD",
            "site:ST", "site:TD", "site:TL"
          ) &&
          SeedingDays > 24
        )
      - HasAnyTag("not-linked") && SeedingDays > 24

    tag:
      - { name: activity:1d,   update: ['LastActivityDays < 7'] }
      - { name: activity:7d,   update: ['LastActivityDays >= 7 && LastActivityDays < 14'] }
      - { name: activity:14d,  update: ['LastActivityDays >= 14 && LastActivityDays < 30'] }
      - { name: activity:30d,  update: ['LastActivityDays >= 30 && LastActivityDays < 180'] }
      - { name: activity:180d, update: ['LastActivityDays >= 180'] }
      - { name: added:1d,      update: ['AddedDays < 7'] }
      - { name: added:7d,      update: ['AddedDays >= 7 && AddedDays < 14'] }
      - { name: added:14d,     update: ['AddedDays >= 14 && AddedDays < 30'] }
      - { name: added:30d,     update: ['AddedDays >= 30 && AddedDays < 180'] }
      - { name: added:180d,    update: ['AddedDays >= 180'] }
      - { name: not-linked,    update: ['HardlinkedOutsideClient == false && Label in ["sonarr", "radarr"]'] }
      - { name: site:ANT,      update: ['TrackerName == "anthelion.me"'] }
      - { name: site:AR,       update: ['TrackerName == "alpharatio.cc"'] }
      - { name: site:AT,       update: ['TrackerName == "animetorrents.me"'] }
      - { name: site:BLU,      update: ['TrackerName in ["blutopia.cc", "blutopia.xyz"]'] }
      - { name: site:FL,       update: ['TrackerName in ["filelist.io", "thefl.org"]'] }
      - { name: site:FNP,      update: ['TrackerName == "fearnopeer.com"'] }
      - { name: site:HDT,      update: ['TrackerName == "hdts-announce.ru"'] }
      - { name: site:IPT,      update: ['TrackerName in ["bgp.technology", "empirehost.me", "stackoverflow.tech"]'] }
      - { name: site:MLK,      update: ['TrackerName == "milkie.cc"'] }
      - { name: site:PHD,      update: ['TrackerName == "privatehd.to"'] }
      - { name: site:ST,       update: ['TrackerName == "scenetime.com"'] }
      - { name: site:TD,       update: ['TrackerName in ["jumbohostpro.eu", "td-peers.com"]'] }
      - { name: site:TL,       update: ['TrackerName in ["tleechreload.org", "torrentleech.org"]'] }
      - { name: tracker-down,  update: ['IsTrackerDown()'] }
      - { name: unregistered,  update: ['IsUnregistered()'] }
