---
clients:
  qb:
    download_path: /media/downloads/torrents/complete
    enabled: true
    filter: default
    type: qbittorrent
    url: http://qbittorrent.media.svc.cluster.local:8080

filters:
  default:
    MapHardlinksFor:
      - retag

    ignore:
      - IsTrackerDown()
      - Downloaded == false && !IsUnregistered()
      - SeedingHours < 26 && !IsUnregistered()

    remove:
      - IsUnregistered()
      - (
          HasAnyTag(
            "site:ant", "site:ar", "site:at", "site:fl", "site:fnp",
            "site:ipt", "site:mlk", "site:td",
          ) &&
          Ratio > 3.0
        )
      - (
          HasAnyTag(
            "site:ant", "site:ar", "site:at", "site:blu", "site:fl",
            "site:fnp", "site:hdt", "site:ipt", "site:mlk", "site:phd",
            "site:st", "site:td", "site:tl"
          ) &&
          SeedingDays > 24
        )
      - HasAnyTag("not-linked") && SeedingDays > 24

    tag:
      - { name: activity:1d,   update: ['LastActivityDays < 7'] }
      - { name: activity:7d,   update: ['LastActivityDays >= 7 && LastActivityDays < 14'] }
      - { name: activity:14d,  update: ['LastActivityDays >= 14 && LastActivityDays < 30'] }
      - { name: activity:30d,  update: ['LastActivityDays >= 30 && LastActivityDays < 180'] }
      - { name: activity:180d, update: ['LastActivityDays >= 180'] }
      - { name: added:1d,      update: ['AddedDays < 7'] }
      - { name: added:7d,      update: ['AddedDays >= 7 && AddedDays < 14'] }
      - { name: added:14d,     update: ['AddedDays >= 14 && AddedDays < 30'] }
      - { name: added:30d,     update: ['AddedDays >= 30 && AddedDays < 180'] }
      - { name: added:180d,    update: ['AddedDays >= 180'] }
      - { name: not-linked,    update: ['HardlinkedOutsideClient == false && Label in ["sonarr", "radarr"]'] }
      - { name: site:ant,      update: ['TrackerName == "anthelion.me"'] }
      - { name: site:ar,       update: ['TrackerName == "alpharatio.cc"'] }
      - { name: site:at,       update: ['TrackerName == "animetorrents.me"'] }
      - { name: site:blu,      update: ['TrackerName in ["blutopia.cc", "blutopia.xyz"]'] }
      - { name: site:fl,       update: ['TrackerName in ["filelist.io", "thefl.org"]'] }
      - { name: site:fnp,      update: ['TrackerName == "fearnopeer.com"'] }
      - { name: site:hdt,      update: ['TrackerName == "hdts-announce.ru"'] }
      - { name: site:ipt,      update: ['TrackerName in ["bgp.technology", "empirehost.me", "stackoverflow.tech"]'] }
      - { name: site:mlk,      update: ['TrackerName == "milkie.cc"'] }
      - { name: site:phd,      update: ['TrackerName == "privatehd.to"'] }
      - { name: site:st,       update: ['TrackerName == "scenetime.com"'] }
      - { name: site:td,       update: ['TrackerName in ["jumbohostpro.eu", "td-peers.com"]'] }
      - { name: site:tl,       update: ['TrackerName in ["tleechreload.org", "torrentleech.org"]'] }
      - { name: tracker-down,  update: ['IsTrackerDown()'] }
      - { name: unregistered,  update: ['IsUnregistered()'] }
