---
clients:
  qb:
    download_path: /media/downloads/torrents/complete
    enabled: true
    filter: default
    type: qbittorrent
    url: http://qbittorrent.media.svc.cluster.local:8080

filters:
  default:
    MapHardlinksFor:
      - retag

    ignore:
      - IsTrackerDown()
      - Downloaded == false && !IsUnregistered()
      - SeedingHours < 26 && !IsUnregistered()

    remove:
      - IsUnregistered()
      - (
          HasAnyTag(
            "site:ant", "site:ar", "site:at", "site:fl", "site:fnp",
            "site:ipt", "site:mlk", "site:td",
          ) &&
          Ratio > 3.0
        )
      - (
          HasAnyTag(
            "site:ant", "site:ar", "site:at", "site:blu", "site:fl",
            "site:fnp", "site:hdt", "site:ipt", "site:mlk", "site:phd",
            "site:st", "site:td", "site:tl"
          ) &&
          SeedingDays > 24
        )
      - HasAnyTag("not-linked") && SeedingDays > 24

    tag:
      - { name: added:1d,     mode: full, update: ['AddedDays < 7'] }
      - { name: added:7d,     mode: full, update: ['AddedDays >= 7 && AddedDays < 14'] }
      - { name: added:14d,    mode: full, update: ['AddedDays >= 14 && AddedDays < 30'] }
      - { name: added:30d,    mode: full, update: ['AddedDays >= 30 && AddedDays < 180'] }
      - { name: added:180d,   mode: full, update: ['AddedDays >= 180'] }
      - { name: not-linked,   mode: full, update: ['HardlinkedOutsideClient == false && Label in ["sonarr", "radarr"]'] }
      - { name: site:ant,     mode: full, update: ['TrackerName == "anthelion.me"'] }
      - { name: site:ar,      mode: full, update: ['TrackerName == "alpharatio.cc"'] }
      - { name: site:at,      mode: full, update: ['TrackerName == "animetorrents.me"'] }
      - { name: site:blu,     mode: full, update: ['TrackerName in ["blutopia.cc", "blutopia.xyz"]'] }
      - { name: site:fl,      mode: full, update: ['TrackerName in ["filelist.io", "thefl.org"]'] }
      - { name: site:fnp,     mode: full, update: ['TrackerName == "fearnopeer.com"'] }
      - { name: site:hdt,     mode: full, update: ['TrackerName == "hdts-announce.ru"'] }
      - { name: site:ipt,     mode: full, update: ['TrackerName in ["bgp.technology", "empirehost.me", "stackoverflow.tech"]'] }
      - { name: site:mlk,     mode: full, update: ['TrackerName == "milkie.cc"'] }
      - { name: site:phd,     mode: full, update: ['TrackerName == "privatehd.to"'] }
      - { name: site:st,      mode: full, update: ['TrackerName == "scenetime.com"'] }
      - { name: site:td,      mode: full, update: ['TrackerName in ["jumbohostpro.eu", "td-peers.com"]'] }
      - { name: site:tl,      mode: full, update: ['TrackerName in ["tleechreload.org", "torrentleech.org"]'] }
      - { name: tracker-down, mode: full, update: ['IsTrackerDown()'] }
      - { name: unregistered, mode: full, update: ['IsUnregistered()'] }
