---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: redis
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: redis
      version: 19.0.1
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    auth:
      enabled: false
      sentinel: false
    master:
      persistence:
        enabled: false
      resourcesPreset: none
    replica:
      persistence:
        enabled: false
      resourcesPreset: none
    sentinel:
      enabled: true
      masterSet: redis-master
      getMasterTimeout: 10
      startupProbe:
        failureThreshold: 2
      persistence:
        enabled: false
      resourcesPreset: none
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 1m
    networkPolicy:
      enabled: false
