---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-recyclarr
  namespace: flux-system
spec:
  targetNamespace: media
  dependsOn:
    - name: cluster-apps-sonarr
    - name: cluster-apps-radarr
    - name: cluster-apps-volsync
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-democratic-csi-local-hostpath
  path: ./kubernetes/apps/media/recyclarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
