---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/buroa/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: home-assistant-secret
        containers:
          app:
            image:
              repository: ghcr.io/buroa/home-assistant
              tag: 2025.2.4@sha256:c7b14ee1237e938130d4080848ad23bbaf0ea858844e3e3ec86f3b4069ce1433
            env:
              HOME_ASSISTANT_EXTERNAL_URL: https://hass.${PUBLIC_DOMAIN}
              HOME_ASSISTANT_PURGE_KEEP_DAYS: 30
              HOME_ASSISTANT_TRUSTED_PROXIES: ${CLUSTER_POD_CIDR}
              HOME_ASSISTANT_UNIT_SYSTEM: imperial
              TZ: ${TIMEZONE}
            envFrom: *envFrom
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "multus-iot",
            "namespace": "networking",
            "ips": ["192.168.99.254/24"],
            "mac": "00:00:00:00:30:00"
          }]
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    ingress:
      app:
        className: internal
        annotations:
          hajimari.io/icon: mdi:home-assistant
          hajimari.io/url: https://hass.${PUBLIC_DOMAIN}
        hosts:
          - host: &host "{{ .Release.Name }}.${PUBLIC_DOMAIN}"
            paths: &paths
              - path: /
                service:
                  identifier: app
                  port: http
          - host: &customHost hass.${PUBLIC_DOMAIN}
            paths: *paths
        tls:
          - hosts:
              - *host
              - *customHost
    persistence:
      config:
        existingClaim: *app
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      tmp:
        type: emptyDir
      tts:
        type: emptyDir
        globalMounts:
          - path: /config/tts
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8123
