---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: alertmanager-silencer
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      alertmanager-silencer:
        type: cronjob
        cronjob:
          schedule: "@daily"
          successfulJobsHistory: 1
          failedJobsHistory: 1
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/kubanetics
              tag: 2024.5.2@sha256:4cea050d5ea2f27c15ab45b07a9335c193bd11d7ca6c4c45ceadc0cdbb1659a2
            env:
              SCRIPT_NAME: alertmanager-silencer.sh
              ALERTMANAGER_URL: http://alertmanager-operated.monitoring.svc.cluster.local:9093
              MATCHERS_0: alertname=KubeAPIErrorBudgetBurn
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
        pod:
          dnsConfig:
            options:
              - name: ndots
                value: "1"
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
