---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: autobrr
      app.kubernetes.io/instance: autobrr
