---
apiVersion: batch/v1
kind: Job
metadata:
  name: "wipe-${rsrc}-${claim}-${ts}"
  namespace: "${namespace}"
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: OnFailure
      containers:
        - name: wipe
          image: ghcr.io/onedr0p/alpine:3.18.4@sha256:f4f467263cf0cfcd9c9ec2a42f5bea147c53732e56c19d558c9369897530e03c
          command: ["/bin/bash", "-c", "cd /config; find . -delete"]
          volumeMounts:
            - name: config
              mountPath: /config
          securityContext:
            privileged: true
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: "${claim}"
