---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snapshot-controller
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: snapshot-controller
      version: 1.9.1
      sourceRef:
        kind: HelmRepository
        name: piraeus-charts
        namespace: flux-system
  maxHistory: 2
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    args:
      v: 5
      httpEndpoint: ":8080"
      leaderElection: true
      leaderElectionNamespace: "$(NAMESPACE)"
      enable-distributed-snapshotting: true
    serviceMonitor:
      create: true
