---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actions-runner-controller.yaml
  - ./backube.yaml
  - ./cilium.yaml
  - ./democratic-csi.yaml
  - ./external-dns.yaml
  - ./grafana.yaml
  - ./intel.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./node-feature-discovery.yaml
  - ./piraeus.yaml
