---
clusterName: &cluster k8s

clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.245.0.0/16

talosVersion: v1.5.3
kubernetesVersion: 1.28.2
endpoint: https://k8s.${domainName}:6443

additionalApiServerCertSans:
  - ${clusterEndpointIP}

additionalMachineCertSans:
  - ${clusterEndpointIP}
  - k8s.${domainName}

cniConfig:
  name: none

nodes:
  - hostname: m0.k8s.${domainName}
    ipAddress: 10.0.5.2
    installDiskSelector:
      serial: S465NB0K748379B
    machineDisks:
      - device: /dev/disk/by-id/ata-CT500MX500SSD1_1825E14523DD
        partitions:
          - mountpoint: /var/mnt/sata
    controlPlane: true
    disableSearchDomain: true
    nameservers:
      - 10.0.1.1
    networkInterfaces:
      - interface: bond0
        bond:
          mode: 802.3ad
          deviceSelectors:
            - hardwareAddr: 94:c6:91:1e:40:5c
              driver: e1000e
        dhcp: false
        mtu: 1500
        vlans:
          - vlanId: 50
            dhcp: false
            addresses:
              - 10.0.5.2/24
            mtu: 1500
            routes:
              - network: 0.0.0.0/0
                gateway: 10.0.5.1
            vip:
              ip: ${clusterEndpointIP}
          - vlanId: 99
            dhcp: false
            addresses:
              - 192.168.99.2/24
            mtu: 1500
          - vlanId: 2
            dhcp: false
            addresses:
              - 10.0.2.2/24
            mtu: 1500
    nodeLabels:
      topology.kubernetes.io/region: *cluster
      topology.kubernetes.io/zone: m

controlPlane:
  patches:
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:admin
            allowedKubernetesNamespaces:
              - kube-system
  inlinePatch:
    cluster:
      allowSchedulingOnMasters: true
      proxy:
        disabled: true
      etcd:
        extraArgs:
          listen-metrics-urls: http://0.0.0.0:2381
        advertisedSubnets:
          - 10.0.5.0/24
      controllerManager:
        extraArgs:
          bind-address: 0.0.0.0
      scheduler:
        extraArgs:
          bind-address: 0.0.0.0
      apiServer:
        admissionControl: null
      discovery:
        registries:
          service:
            disabled: true
    machine: &machine
      install:
        image: ghcr.io/siderolabs/installer:v1.5.3
        extensions:
          - image: ghcr.io/siderolabs/i915-ucode:20230804
          - image: ghcr.io/siderolabs/intel-ucode:20230808
          - image: ghcr.io/siderolabs/thunderbolt:v1.5.3
        legacyBIOSSupport: true
        extraKernelArgs:
          - talos.logging.kernel=udp://vector.${domainName}:6001/
      features:
        kubePrism:
          enabled: true
          port: 7445
      logging:
        destinations:
          - endpoint: udp://vector.${domainName}:6002/
            format: json_lines
      sysctls:
        fs.inotify.max_user_watches: 1048576
        fs.inotify.max_user_instances: 8192
        kernel.randomize_va_space: 0
        net.core.netdev_max_backlog: 30000
        net.core.rmem_max: 67108864
        net.core.wmem_max: 67108864
        net.ipv4.tcp_rmem: 4096 87380 33554432
        net.ipv4.tcp_wmem: 4096 65536 33554432
        net.ipv4.tcp_tw_reuse: 1
        net.ipv4.tcp_window_scaling: 1
      udev:
        rules:
          - ACTION=="add", SUBSYSTEM=="thunderbolt", ATTR{authorized}=="0", ATTR{authorized}="1"
      network:
        extraHostEntries:
          - ip: ${clusterEndpointIP}
            aliases:
              - k8s.${domainName}
          - ip: 10.0.1.1
            aliases:
              - unifi.${domainName}
          - ip: 10.0.1.10
            aliases:
              - nas.${domainName}
          - ip: 10.0.0.6
            aliases:
              - ups.${domainName}
          - ip: 10.0.0.7
            aliases:
              - pdu.${domainName}
          - ip: 10.0.3.4
            aliases:
              - vector.${domainName}
      time:
        disabled: false
        servers:
          - time.cloudflare.com
      kubelet:
        extraArgs:
          feature-gates: GracefulNodeShutdown=true
          rotate-server-certificates: true
        extraConfig:
          maxPods: 150
        extraMounts:
          - destination: /var/mnt/sata
            type: bind
            source: /var/mnt/sata
            options:
              - rbind
              - rshared
              - rw
        nodeIP:
          validSubnets:
            - 10.0.5.0/24
      files:
        - content: |
            [plugins."io.containerd.grpc.v1.cri"]
              enable_unprivileged_ports = true
              enable_unprivileged_icmp = true
          path: /etc/cri/conf.d/20-customization.part
          op: create

worker:
  inlinePatch:
    machine:
      <<: *machine
