---
clusterName: &cluster k8s

clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.245.0.0/16

endpoint: https://k8s.${PUBLIC_DOMAIN}:6443

# renovate: depName=ghcr.io/siderolabs/installer datasource=docker
talosVersion: v1.6.6
# renovate: depName=ghcr.io/siderolabs/kubelet datasource=docker
kubernetesVersion: v1.29.2

additionalApiServerCertSans: &sans
  - ${CLUSTER_ENDPOINT_IP}
  - k8s.${PUBLIC_DOMAIN}
  - 127.0.0.1 # KubePrism

additionalMachineCertSans: *sans

cniConfig:
  name: none

nodes:
  - hostname: m0.k8s.${PUBLIC_DOMAIN}
    ipAddress: 10.0.5.2
    installDiskSelector:
      serial: S465NB0K748379B
    machineDisks:
      - device: /dev/disk/by-id/ata-CT4000MX500SSD1_2336E873A309
        partitions:
          - mountpoint: /var/mnt/sata
    controlPlane: true
    networkInterfaces:
      - interface: bond0
        bond:
          mode: 802.3ad
          miimon: 100
          deviceSelectors:
            - hardwareAddr: 94:c6:91:1e:40:5c
              driver: e1000e
        dhcp: false
        mtu: 1500
        vlans:
          - vlanId: 50
            dhcp: false
            addresses:
              - 10.0.5.2/24
            mtu: 1500
            routes:
              - network: 0.0.0.0/0
                gateway: 10.0.5.1
            vip:
              ip: ${CLUSTER_ENDPOINT_IP}
          - vlanId: 99
            dhcp: false
            addresses:
              - 192.168.99.2/24
            mtu: 1500
          - vlanId: 2
            dhcp: false
            addresses:
              - 10.0.2.2/24
            mtu: 1500
    patches:
      - |-
        machine:
          kubelet:
            extraMounts:
              - destination: /var/mnt/sata
                type: bind
                source: /var/mnt/sata
                options:
                  - rbind
                  - rshared
                  - rw

controlPlane:
  nodeLabels:
    topology.kubernetes.io/region: *cluster
    topology.kubernetes.io/zone: m

  schematic: &schematic
    customization:
      extraKernelArgs:
        - mitigations=off
        - net.ifnames=0
      systemExtensions:
        officialExtensions:
          - siderolabs/intel-ucode
          - siderolabs/i915-ucode
          - siderolabs/thunderbolt

  patches:
    # Configure containerd
    - &containerdPatch |-
      machine:
        files:
          - op: create
            path: /etc/cri/conf.d/20-customization.part
            content: |-
              [plugins."io.containerd.grpc.v1.cri"]
                enable_unprivileged_ports = true
                enable_unprivileged_icmp = true

    # Disable search domain everywhere
    - &disableSearchDomainPatch |-
      machine:
        network:
          disableSearchDomain: true

    # Enable cluster discovery
    - &discoveryPatch |-
      cluster:
        discovery:
          registries:
            kubernetes:
              disabled: false
            service:
              disabled: true

    # Configure kubelet
    - &kubeletPatch |-
      machine:
        kubelet:
          extraArgs:
            feature-gates: GracefulNodeShutdown=true
            rotate-server-certificates: true
          extraConfig:
            maxPods: 200
          nodeIP:
            validSubnets:
              - 10.0.5.0/24

    # Enable KubePrism
    - &kubePrismPatch |-
      machine:
        features:
          kubePrism:
            enabled: true
            port: 7445

    # Force nameserver
    - &nameserverPatch |-
      machine:
        network:
          nameservers:
            - 10.0.1.1

    # Configure NFS mount options
    - &nfsPatch |-
      machine:
        files:
          - op: overwrite
            path: /etc/nfsmount.conf
            permissions: 0o644
            content: |
              [ NFSMount_Global_Options ]
              nfsvers=4.1
              hard=True
              noatime=True
              nodiratime=True
              rsize=131072
              wsize=131072
              nconnect=8

    # Configure NTP
    - &ntpPatch |-
      machine:
        time:
          disabled: false
          servers:
            - time.cloudflare.com

    # Static host entries
    - &staticHostEntriesPatch |-
      machine:
        network:
          extraHostEntries:
            - ip: ${CLUSTER_ENDPOINT_IP}
              aliases:
                - k8s.${PUBLIC_DOMAIN}
            - ip: 10.0.1.1
              aliases:
                - unifi.${PUBLIC_DOMAIN}
            - ip: 10.0.1.10
              aliases:
                - nas.${PUBLIC_DOMAIN}

    # Custom sysctl settings
    - &sysctlPatch |-
      machine:
        sysctls:
          fs.inotify.max_user_watches: 1048576
          fs.inotify.max_user_instances: 8192
          kernel.randomize_va_space: 0
          net.core.netdev_max_backlog: 30000
          net.core.rmem_max: 67108864
          net.core.wmem_max: 67108864
          net.ipv4.tcp_rmem: 4096 87380 33554432
          net.ipv4.tcp_wmem: 4096 65536 33554432
          net.ipv4.tcp_tw_reuse: 1
          net.ipv4.tcp_window_scaling: 1

    # Various udev rules
    - &udevPatch |-
      machine:
        udev:
          rules:
            - ACTION=="add", SUBSYSTEM=="thunderbolt", ATTR{authorized}=="0", ATTR{authorized}="1"
            - SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="44", MODE="0660"

    # Cluster configuration
    - |-
      cluster:
        allowSchedulingOnMasters: true
        controllerManager:
          extraArgs:
            bind-address: 0.0.0.0
        coreDNS:
          disabled: true
        proxy:
          disabled: true
        scheduler:
          extraArgs:
            bind-address: 0.0.0.0

    # ETCD configuration
    - |-
      cluster:
        etcd:
          extraArgs:
            listen-metrics-urls: http://0.0.0.0:2381
          advertisedSubnets:
            - 10.0.5.0/24

    # Disable default API server admission plugins.
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl

    # Enable K8s Talos API Access
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:admin
            allowedKubernetesNamespaces:
              - kube-system

worker:
  nodeLabels:
    topology.kubernetes.io/region: *cluster
    topology.kubernetes.io/zone: w

  schematic: *schematic

  patches:
    - *containerdPatch
    - *disableSearchDomainPatch
    - *discoveryPatch
    - *kubeletPatch
    - *kubePrismPatch
    - *nameserverPatch
    - *nfsPatch
    - *ntpPatch
    - *staticHostEntriesPatch
    - *sysctlPatch
    - *udevPatch
