---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/New_York

  # Domains
  PUBLIC_DOMAIN: youmans.io
  PUBLIC_EMAIL: brandtyoumans@gmail.com

  # Storage
  CLUSTER_STORAGE_HOSTPATH: "democratic-csi-local-hostpath"
  CLUSTER_SNAPSHOT_HOSTPATH: "democratic-csi-local-hostpath"

  # K8s
  CLUSTER_SERVICE_IP_CIDR: "10.245.0.0/16"
  CLUSTER_POD_IP_CIDR: "10.244.0.0/16"
  CLUSTER_API_IP: "10.0.5.3"
  CLUSTER_DNS_IP: "10.245.0.10"
  SMTP_RELAY_IP: "10.245.0.25"
  K8S_GATEWAY_IP: "10.245.0.53"

  # Cilium
  CILIUM_LB_CIDR: "10.0.2.0/24"
  TORRENT_LB_IP: "10.0.2.3"
  TAILSCALE_LB_IP: "10.0.2.4"
  VECTOR_LB_IP: "10.0.2.5"
  BLOCKY_LB_IP: "10.0.2.53"
  INGRESS_LB_IP: "10.0.2.80"

  # LAN
  LAN_TRUSTED_IP_CIDR: "192.168.0.0/24"
  LAN_TRUSTED_GATEWAY_IP: "192.168.0.1"
  LAN_SERVER_IP_CIDR: "10.0.5.0/24"
  LAN_SERVER_GATEWAY_IP: "10.0.5.1"
  LAN_IOT_IP_CIDR: "192.168.99.0/24"
  LAN_IOT_GATEWAY_IP: "192.168.99.1"

  # Shh :-)
  TORRENT_PUBLIC_PORT: "1337"
  TAILNET_PUBLIC_PORT: "41642"
