---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/New_York

  # Domains
  PUBLIC_DOMAIN: youmans.io
  INTERNAL_DOMAIN: internal

  # Email
  PUBLIC_EMAIL: brandtyoumans@gmail.com

  # Storage
  CLUSTER_STORAGE_HOSTPATH: democratic-csi-local-hostpath
  CLUSTER_SNAPSHOT_HOSTPATH: democratic-csi-local-hostpath

  # K8s
  CLUSTER_POD_CIDR: 10.244.0.0/16
  CLUSTER_SERVICE_CIDR: 10.245.0.0/16

  # Networks
  NET_INTERNAL_CIDR: 10.0.1.0/24
  NET_VM_CIDR: 10.0.5.0/24
  NET_IOT_CIDR: 192.168.99.0/24
  NET_SERVICES_CIDR: 10.0.2.0/24

  # Gateways
  NET_INTERNAL_GATEWAY_IP: 10.0.1.1
  NET_IOT_GATEWAY_IP: 192.168.99.1

  # Services
  NET_SERVICES_QBITTORRENT_IP: 10.0.2.2
  NET_SERVICES_INGRESS_IP_EXT: 10.0.2.80
  NET_SERVICES_INGRESS_IP_INT: 10.0.2.81

  # Shh :-)
  NET_SERVICES_QBITTORRENT_PORT: "50415"
