---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./datasource
configMapGenerator:
  - name: blocky-config-tpl
    files:
      - ./configs/config.yml
generatorOptions:
  disableNameSuffixHash: true
labels:
  - pairs:
      app.kubernetes.io/name: blocky
      app.kubernetes.io/instance: blocky
