---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app plex
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      plex:
        containers:
          app:
            image:
              repository: ghcr.io/buroa/plex
              tag: 1.41.3.9314-a0bfb8370@sha256:e928b7d787bc98dcb579f41f10f9002ff85ed2fd618633704792a2f5480b6909
            env:
              PLEX_ADVERTISE_URL: https://{{ .Release.Name }}.${PUBLIC_DOMAIN}:443
              PLEX_NO_AUTH_NETWORKS: ${NET_INTERNAL_CIDR}
              TZ: ${TIMEZONE}
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: &path /identity
                    port: &port 32400
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              limits:
                gpu.intel.com/i915: 1
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: "true"
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 44
          - 65537
    ingress:
      app:
        className: external
        annotations:
          gatus.io/path: *path
          hajimari.io/icon: mdi:plex
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        hosts:
          - host: &host "{{ .Release.Name }}.${PUBLIC_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      cache:
        existingClaim: plex-cache
        globalMounts:
          - path: /config/Library/Application Support/Plex Media Server/Cache
      config:
        existingClaim: *app
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/Library/Application Support/Plex Media Server/Logs
      media:
        type: nfs
        server: nas.${INTERNAL_DOMAIN}
        path: /volume1/PLEX
        globalMounts:
          - readOnly: true
      tmp:
        type: emptyDir
      transcode:
        type: emptyDir
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
