---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app snmp-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-snmp-exporter
      version: 5.6.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    image:
      repository: quay.io/prometheus/snmp-exporter
    serviceMonitor:
      enabled: true
      params:
        - name: nas
          auth: [public_v1]
          module: [synology]
          target: nas.${INTERNAL_DOMAIN}
      path: /snmp
      scrapeTimeout: 10s
