---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbtools
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      tagging:
        type: cronjob
        cronjob: &cronjob
          schedule: "@hourly"
          timeZone: &timeZone ${TIMEZONE}
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
        initContainers:
          tagging: &container
            image:
              repository: ghcr.io/buroa/qbtools
              tag: v0.19.14@sha256:905617dfc1a8aa1510381d8e177cc5581a49bfa9d56f3f05e0574f6c83987d3c
            args:
              - tagging
              - --added-on
              - --expired
              - --last-activity
              - --sites
              - --unregistered
            env:
              QBITTORRENT_HOST: qbittorrent.media.svc.cluster.local
              QBITTORRENT_PORT: 8080
              TZ: *timeZone
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
        containers:
          unregistered:
            <<: *container
            args:
              - prune
              - --exclude-tag=expired
              - --exclude-tag=added:24h
              - --include-tag=unregistered
          expired:
            <<: *container
            args:
              - prune
              - --exclude-category=manual
              - --exclude-tag=activity:24h
              - --include-tag=expired
        pod:
          restartPolicy: OnFailure
          securityContext: &podSecurityContext
            runAsNonRoot: true
            runAsUser: 568
            runAsGroup: 568
      orphaned:
        type: cronjob
        cronjob:
          <<: *cronjob
          schedule: "@daily"
        containers:
          app:
            <<: *container
            args:
              - orphaned
              - --exclude-pattern="*_unpackerred"
              - --exclude-pattern="*/manual/*"
        pod:
          restartPolicy: OnFailure
          securityContext:
            <<: *podSecurityContext
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 65536
      reannounce:
        containers:
          app:
            <<: *container
            args:
              - reannounce
        pod:
          securityContext: *podSecurityContext
    persistence:
      config:
        type: configMap
        name: qbtools-configmap
        advancedMounts:
          tagging:
            tagging:
              - path: /config/config.yaml
                subPath: config.yaml
                readOnly: true
      media:
        type: nfs
        server: nas.${INTERNAL_DOMAIN}
        path: /volume1/PLEX
