---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: multus
spec:
  interval: 30m
  chart:
    spec:
      chart: multus
      version: 5.0.7
      sourceRef:
        kind: HelmRepository
        name: angelnu-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    image:
      repository: ghcr.io/k8snetworkplumbingwg/multus-cni
      tag: v4.1.4-thick@sha256:df8c2963d8356484a856d9949d2f0150ed1d430f5b0979fa041d04eb2bce6403
    cni:
      image:
        repository: ghcr.io/angelnu/cni-plugins
        tag: 1.6.1@sha256:a5a7976ba17b405072143c61ee55660d170eb974e0f50fb39acb365458a47a7f
      logLevel: error
      paths:
        bin: /opt/cni/bin
        config: /etc/cni/net.d
    hostPaths:
      netns: /var/run/netns
  postRenderers:
    - kustomize:
        patches:
          - patch: |-
              apiVersion: apps/v1
              kind: DaemonSet
              metadata:
                name: multus
              spec:
                template:
                  metadata:
                    labels:
                      webhooks.kyverno.io/exclude: "true"
