---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopia
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kopia-secret
    template:
      data:
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
      templateFrom:
        - configMap:
            name: kopia-configmap-tpl
            items:
              - key: repository.config
  dataFrom:
    - extract:
        key: cloudflare
    - extract:
        key: volsync-template
