---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopia
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kopia-secret
    template:
      templateFrom:
        - configMap:
            name: kopia-configmap-tpl
            items:
              - key: repository.config
  dataFrom:
    - extract:
        key: cloudflare
    - extract:
        key: volsync-template
