---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: youmans-io
spec:
  secretName: youmans-io-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: youmans.io
  dnsNames: ["youmans.io", "*.youmans.io"]
