---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: multus-iot
  namespace: networking
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-iot",
      "plugins": [
        {
          "type": "macvlan",
          "master": "bond0.2",
          "mode": "bridge",
          "capabilities": {
            "ips": true
          },
          "ipam": {
            "type": "static",
            "routes": [
              { "dst": "${LAN_TRUSTED_IP_CIDR}", "gw": "192.168.2.1" },
              { "dst": "${LAN_SERVER_IP_CIDR}", "gw": "192.168.2.1" },
              { "dst": "${LAN_IOT_IP_CIDR}", "gw": "192.168.2.1" }
            ]
          }
        }
      ]
    }
