---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k13-dev
spec:
  secretName: k13-dev-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: youmans.io
  dnsNames: ["youmans.io", "*.youmans.io"]
