---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app lldap
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      lldap:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/buroa/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: lldap-secret
        containers:
          app:
            image:
              # TODO: Update the image to a semver tag
              repository: ghcr.io/lldap/lldap
              tag: latest-alpine-rootless@sha256:876a6b4cdb64523a44a8416b9e50d30b626b14347df0028b642b50729089f8d0
            env:
              TZ: ${TIMEZONE}
              LLDAP_HTTP_PORT: &httpPort 80
              LLDAP_LDAP_PORT: &ldapPort 389
              LLDAP_LDAP_BASE_DN: dc=home,dc=arpa
              LLDAP_HTTP_URL: https://{{ .Release.Name }}.${PUBLIC_DOMAIN}
              LLDAP_SMTP_OPTIONS__PORT: 25
              LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION: NONE
              LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET: true
              LLDAP_SMTP_OPTIONS__FROM: LLDAP <{{ .Release.Name }}@${PUBLIC_DOMAIN}>
              LLDAP_SMTP_OPTIONS__SERVER: smtp-relay.networking.svc.cluster.local
            envFrom: *envFrom
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *httpPort
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app
    ingress:
      app:
        className: internal
        annotations:
          hajimari.io/icon: mdi:account-lock
        hosts:
          - host: &host "{{ .Release.Name }}.${PUBLIC_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      data:
        type: emptyDir
    service:
      app:
        controller: *app
        ports:
          http:
            port: *httpPort
          ldap:
            port: *ldapPort
