---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app gha-runner-scale-set
spec:
  interval: 30m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.10.1
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    nameOverride: *app
    runnerScaleSetName: *app
    githubConfigUrl: https://github.com/dotcomscripts/k8s-gitops
    minRunners: 1
    maxRunners: 3
    containerMode:
      type: dind
    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/buroa/actions-runner:2.321.0@sha256:d28622cbd00742d45f180f3ebb24c24880311a7188f1344f240f2f3ba4a15336
            command:
              - /home/runner/run.sh
    controllerServiceAccount:
      name: gha-runner-scale-set-controller
      namespace: actions-runner-system
  valuesFrom:
    - kind: Secret
      name: actions-runner-controller-secret
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID
      targetPath: githubConfigSecret.github_app_id
    - kind: Secret
      name: actions-runner-controller-secret
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_INSTALLATION_ID
      targetPath: githubConfigSecret.github_app_installation_id
    - kind: Secret
      name: actions-runner-controller-secret
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_PRIVATE_KEY
      targetPath: githubConfigSecret.github_app_private_key
