---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app gha-runner-scale-set
spec:
  interval: 30m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.9.0
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    nameOverride: *app
    runnerScaleSetName: *app
    githubConfigUrl: https://github.com/dotcomscripts/k8s-gitops
    minRunners: 1
    maxRunners: 3
    containerMode:
      type: dind
    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/buroa/actions-runner:2.315.0@sha256:9371150f86655331d0bdb36d01c74acb56954b63ad360954746b5165248969e1
            command:
              - /home/runner/run.sh
    controllerServiceAccount:
      name: gha-runner-scale-set-controller
      namespace: actions-runner-system
  valuesFrom:
    - kind: Secret
      name: actions-runner-controller-secret
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID
      targetPath: githubConfigSecret.github_app_id
    - kind: Secret
      name: actions-runner-controller-secret
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_INSTALLATION_ID
      targetPath: githubConfigSecret.github_app_installation_id
    - kind: Secret
      name: actions-runner-controller-secret
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_PRIVATE_KEY
      targetPath: githubConfigSecret.github_app_private_key
